### ISSUE TITLE
Loss of data integrity with threading from OnNewMessage()

### ISSUE THREAD

**Issue by derMaaster** [epam/fix-antenna-net-core#104]
Hi,

I am sure this is not actually an issues with the fix-antenna-net-core library, so feel free to close this issue if my posting here is inappropriate.

I get a false return on `fixMessage.IsTagExists(268)` even though all the message cleary has Tag268 included in the messages according to the log file.

My code example [here](https://stackoverflow.com/questions/77920487/loss-of-data-integrity-when-consuming-incoming-fix-market-messages-using-actionb?noredirect=1#comment137370264_77920487)

(This happens on 35=X incoming messages, where 268 is a required field according to the providers dictionary)

**Comment by derMaaster** [comment]
Definitely losing data integrity from before OnNewMessage() writes to a Channel and when a new thread reads from the Channel

**Comment by viktartse** [comment]
Hi @derMaaster, one thing that is definitely should be done if there is a need to process the received message later is cloning the message. The engine re-uses the same chunk of memory for every FixMessage that is passed to the OnNewMessage handler.
To clone the message you can do something like this:

`var messageCopy = (FixMessage)message.Clone();`

**Comment by Viktar-Tserashchuk** [comment]
I agree a call to .Clone is not very cheap but an alternative would be the engine constructing a new FixMessage object for every new message from scratch instead of reusing the same object. That would also have a cost.
