### ISSUE TITLE
Support FixMessage.Parse

### ISSUE THREAD

**Issue by DHirani** [epam/fix-antenna-net-core#15]
Will you be supporting FixMessage.Parse which is supported by the .net version that is wrapped around C library? 

also will you support all the features and is there a page showing how to port your code to this library from the current .net framework version?

**Comment by epm-sergem** [comment]
You could use [RawFixUtil.GetFixMessage](https://github.com/epam/fix-antenna-net-core/blob/340f449c9f99296bdd4939eb3902681eea94f084/FixAntenna/NetCore/Message/RawFixUtil.cs#L611) for parsing string or byte array to FixMessage.
What other features are you interested in? API of .NET Core and .NET (wrapper) version are quite different.

**Comment by DHirani** [comment]
Thank you RawFixUtil utility, however if we want to move from Net (Wrapper) to .Net Core is there good articles, also my understanding is that .Net Wrapper will be obsolete as .Net Core will be the future, correct?
