### ISSUE TITLE
ByteArrayMessageStorage.Add: Suspicious code

### ISSUE THREAD

**Issue by ujos** [epam/fix-antenna-net-core#52]
Usually `offset` and `length` are related to the input `byte[]` parameter. However in the following code the `offset` parameter is treated as `destinationIndex`.  Why is that?

```csharp
// ByteArrayMessageStorage class
public override void Add(int tagIndex, byte[] value, int offset, int length)
{
    Array.Copy(value, 0, _origBuffer, offset, length);
}
```

**Comment by OlehVasylievEPAM** [comment]
Fix Antenna .NET Core was ported from JAVA, I think this is the reason for incorrect naming. Anyway, thank you for your feedback, we will create a ticket and fix this issue in near future.

**Comment by ujos** [comment]
It is about naming. Rather about behavior. `ByteArrayMessageStorage` treats `offset` as a offset of the `_originalBuffer`, while `ArenaMessageStorage` treats `offset` as an offset of the `value` parameter

**Comment by OlehVasylievEPAM** [comment]
Got it

**Comment by ujos** [comment]
JFYI, I worked on implementation of the `FixMessage.AddTag(int, ReadOnlySpan)` method. Because of this issue I cannot proceed.

**Comment by OlehVasylievEPAM** [comment]
Hello ujos, your issue is included in release 1.1.1. Please, let me know if you need a hotfix ASAP.

**Comment by ujos** [comment]
> Hello ujos, your issue is included in release 1.1.1. Please, let me know if you need a hotfix ASAP.

@OlehVasylievEPAM , where can I find the code for v1.1.1 ?

**Comment by OlehVasylievEPAM** [comment]
Hello @ujos , it will be here (in the GitHub repo). For now, release 1.1.1 is only planned. Soon we release 1.1.0 with a scheduler JFYI.

**Comment by ujos** [comment]
@OlehVasylievEPAM In case if you have the hotfix ready, please share it with me.

**Comment by OlehVasylievEPAM** [comment]
@ujos, we do not have :(
