### ISSUE TITLE
Question about behavior when param forceSeqNumReset set to OneTime

### ISSUE THREAD

**Issue by analitiq** [epam/fix-antenna-net-core#53]
Hi Everyone!
Thanks a lot for your open source product! I would like to ask about unexpected (for me) actual behavior of FA provided below. Was this expected by design?

**Version of FIX Antenna .NET Core Community Edition: 1.0.4**

**Preconditions**
The following params are specified:

1. fixVersion = FIX.4.4
2. autoreconnectAttempts = 0
3. autoreconnectDelayInMs = 3000
4. forceSeqNumReset = OneTime
5. inMemoryQueue = true
6. storageFactory = Epam.FixAntenna.NetCore.FixEngine.Storage.InMemoryStorageFactory
7. All other params kept with their default values.

No FIX session acceptor which runs.

**Actions**

1. Start FIX session initiator first.
2. Wait until it tried some reconnects.
3. Start FIX session acceptor.

FIX message Logon will be send without tag “141=Y”. It seems like FA send this tag only in first try of connection. If first try was successful, Logon with “141=Y” will be send as expected. But if first try was unsuccessful FA doesn’t set this tag in further reconnects.

**Expected (for me) behavior**
Trying to send Logon with “141=Y” until FIX session will be successfully established once. For example, seems like in such case with similar parameters proprietary FIX Antenna .NET 2.24.0.255 acts as expected.

**Comment by OlehVasylievEPAM** [comment]
Hello analitiq, thank you for your issue. I see what you mean. JFYI, we have this bug in our backlog which will be fixed in release 1.1.1.
Please, let me know if you need a hotfix ASAP.

**Comment by OlehVasylievEPAM** [comment]
Hi analitiq, the new release (1.2.0) is available. The release contains the fix. Thanks for your impact!
